### ISSUE TITLE
Написание ТЗ: ramp up

### ISSUE THREAD

**Issue by DenisRybas** [SP-organization/Awareness#3]
Получить базовое представление о написании ТЗ
Шаги для этого
- Прочитать фрагменты книг, в которых об этом пишут (буду прикреплять то, что изучил в комментарии)
- Посмотреть примеры из интернета
- Посмотреть различные шаблоны и best practices для написания ТЗ
- Пересмотреть фрагменты лекций по ТП, связанные с написанием ТЗ

**Comment by SP-organization** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Написание ТЗ: ramp up](https://trello.com/c/TjJSJTHu/4-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D1%82%D0%B7-ramp-up)
