### ISSUE TITLE
Распределить роли

### ISSUE THREAD

**Issue by DenisRybas** [SP-organization/Awareness#4]
Определить, кто чем будет заниматься в проекте

**Comment by SP-organization** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Распределить роли](https://trello.com/c/wXV1zERk/6-%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C-%D1%80%D0%BE%D0%BB%D0%B8)

**Comment by DenisRybas** [comment]
Рыбас Денис - Lead, PM, основной разработчик BackEnd-части приложения, помощник в разработке FrontEnd
Илья Соболь - основной разработчик FrontEnd-части приложения, помощник в разработке BackEnd
Павел Светачев и Артём Попенко - тестирование приложения, сбор отзывов пользователей
