### ISSUE TITLE
Определиться со стеком технологий

### ISSUE THREAD

**Issue by DenisRybas** [SP-organization/Awareness#6]
На данный момент стек такой:
- Flutter - mobile app
- Firebase - server
Финальный стек будет написан в комментариях

**Comment by SP-organization** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Определиться со стеком технологий](https://trello.com/c/dDX7HoKz/7-%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D1%81%D0%BE-%D1%81%D1%82%D0%B5%D0%BA%D0%BE%D0%BC-%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B9)

**Comment by DenisRybas** [comment]
Финальный стек:
Python, Flask, PostgreSQL для написания бэкенда
JS, CSS, HTML для фронта
